name: Test Python Script

on:
  push:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Rodar scanner de segurança
        run: python scan.py

      - name: Salvar relatório de segurança
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-seguranca
          path: reports/credential_report.json